#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeDoc.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MSP-GeDoc-Desarrollo")]
	public partial class dbcDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbcDatosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MSP_GeDoc_DesarrolloConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbcDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnValidarUsuario", IsComposable=true)]
		public System.Nullable<bool> fnValidarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(255)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pass", DbType="VarChar(255)")] string pass)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, pass).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnPassword", IsComposable=true)]
		public System.Data.Linq.Binary fnPassword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pass", DbType="VarChar(255)")] string pass)
		{
			return ((System.Data.Linq.Binary)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pass).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcRegistrarLogUsuario")]
		public int ProcRegistrarLogUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string luDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> usrId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mnuId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> acId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), luDescripcion, usrId, mnuId, acId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnNumerosALetras", IsComposable=true)]
		public string fnNumerosALetras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> numero)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numero).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProcActualizaUsuario")]
		public int ProcActualizaUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> usrId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string usrNombreDeUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string usrApellidoyNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usrPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> estId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usrEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usrId, usrNombreDeUsuario, usrApellidoyNombre, usrPassword, estId, usrEmail);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnCronosAsistenciaDelDia", IsComposable=true)]
		public IQueryable<fnCronosAsistenciaDelDiaResult> fnCronosAsistenciaDelDia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="BigInt")] System.Nullable<long> dNI, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> perId)
		{
			return this.CreateMethodCallQuery<fnCronosAsistenciaDelDiaResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dNI, perId);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnCronosAsistenciaDeUnDiaEstado", IsComposable=true)]
		public IQueryable<fnCronosAsistenciaDeUnDiaEstadoResult> fnCronosAsistenciaDeUnDiaEstado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="BigInt")] System.Nullable<long> dNI, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> perId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dia", DbType="Int")] System.Nullable<int> dia)
		{
			return this.CreateMethodCallQuery<fnCronosAsistenciaDeUnDiaEstadoResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dNI, perId, dia);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnCronosAsistenciaDelMes", IsComposable=true)]
		public IQueryable<fnCronosAsistenciaDelMesResult> fnCronosAsistenciaDelMes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> perId)
		{
			return this.CreateMethodCallQuery<fnCronosAsistenciaDelMesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), perId);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnCronosAsistenciaDeUnDia", IsComposable=true)]
		public IQueryable<fnCronosAsistenciaDeUnDiaResult> fnCronosAsistenciaDeUnDia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DNI", DbType="BigInt")] System.Nullable<long> dNI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dia", DbType="Int")] System.Nullable<int> dia)
		{
			return this.CreateMethodCallQuery<fnCronosAsistenciaDeUnDiaResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dNI, dia);
		}
	}
	
	public partial class fnCronosAsistenciaDelDiaResult
	{
		
		private System.Nullable<short> _Codigo;
		
		private string _Estado;
		
		public fnCronosAsistenciaDelDiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="SmallInt")]
		public System.Nullable<short> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class fnCronosAsistenciaDeUnDiaEstadoResult
	{
		
		private System.Nullable<short> _Codigo;
		
		private string _Estado;
		
		public fnCronosAsistenciaDeUnDiaEstadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="SmallInt")]
		public System.Nullable<short> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(250)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class fnCronosAsistenciaDelMesResult
	{
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<short> _Codigo;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _Entrada;
		
		private System.Nullable<System.DateTime> _Salida;
		
		public fnCronosAsistenciaDelMesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="SmallInt")]
		public System.Nullable<short> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(250)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this._Entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salida", DbType="DateTime")]
		public System.Nullable<System.DateTime> Salida
		{
			get
			{
				return this._Salida;
			}
			set
			{
				if ((this._Salida != value))
				{
					this._Salida = value;
				}
			}
		}
	}
	
	public partial class fnCronosAsistenciaDeUnDiaResult
	{
		
		private System.Nullable<System.DateTime> _Entrada;
		
		private System.Nullable<System.DateTime> _Salida;
		
		public fnCronosAsistenciaDeUnDiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entrada
		{
			get
			{
				return this._Entrada;
			}
			set
			{
				if ((this._Entrada != value))
				{
					this._Entrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salida", DbType="DateTime")]
		public System.Nullable<System.DateTime> Salida
		{
			get
			{
				return this._Salida;
			}
			set
			{
				if ((this._Salida != value))
				{
					this._Salida = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
